<?php

use Illuminate\Database\Seeder;

use App\ProductOption;
use Carbon\Carbon;

class ProductOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->format('Y-m-d H:i:s');

        ProductOption::insert([
            ['product_id' => 7, 'code' => '195416C1-3447-423A-B37B-EE59A99A19C4', 'msname' => 'Exchange Online (Plan 1)', 'text' => 'Veilige en betrouwbare zakelijke e-mail met een postvak van 50 GB per gebruiker.', 'group' => 'exchange', 'name' => 'Exchange Online', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '2F707C7C-2433-49A5-A437-9CA7CF40D3EB', 'msname' => 'Exchange Online (Plan 2)', 'text' => 'Alle functies van Exchange Online plan 1, maar 100 GB opslag per mailbox, onbeperkte opslag in het in-place archief, gehoste voicemail en preventie van gegevensverlies.', 'group' => 'exchange', 'name' => 'Exchange Online Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'BD938F12-058F-4927-BBA3-AE36B1D2501C', 'msname' => 'Office 365 Business Essentials', 'text' => 'Inclusief e-mail via Exchange Online, online versies van Word, Excel en Powerpoint, Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Planner.  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business Essentials', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '5C9FD4CC-EDCE-44A8-8E91-07DF09744609', 'msname' => 'Office 365 Business', 'text' => 'Inclusief desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - niet compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker).  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '031C9E47-4802-4248-838E-778FB1D2CC05', 'msname' => 'Office 365 Business Premium', 'text' => 'Inclusief e-mail via Exchange Onlinte, desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - niet compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Outlook Customer Manager, Bookings, Planner.  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business Premium', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '91FD106F-4B2C-4938-95AC-F54F74E9A239', 'msname' => 'Office 365 Enterprise E1', 'text' => 'Inclusief e-mail via Exchange Online, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Yammer, Planner. Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 - E1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '796B6B5F-613C-4E24-A17C-EBA730D49C02', 'msname' => 'Office 365 Enterprise E3', 'text' => 'Inclusief e-mail via Exchange Online, desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - compatibel met Remote Desktop Servers), Onenote,online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Yammer, Planner.  Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 - E3', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'BE57FF4C-100C-4F1F-B82D-F1C5AB63A665', 'msname' => 'Office 365 ProPlus', 'text' => 'Inclusief desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker).  Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 Pro Plus', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '61795CAB-2ABD-43F6-88E9-C9ADAE5746E0', 'msname' => 'Microsoft 365 Business', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Office 365 Data Loss Prevention, Windows Information Protectionand Bitlocker, Azure Information Protection P1, Azure Information Protection P2, Microsoft cloudApp Security, Office 365 Cloud App Security, Advanced eDiscovery, Customer Lockbox, AdvancedData Governance', 'group' => 'microsoft', 'name' => 'Microsoft 365 Business', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '2B3B8D2D-10AA-4BE4-B5FD-7F2FEB0C3091', 'msname' => 'Microsoft 365 E3', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Sharepoint Online, Yammer, Microsoft Advanced Threat Analytics,Windows Defender Antivirus, Device Guard, Azure Active Directory P1, Windows Hello and CredentialGuard, Intune, Office 365 Data Loss Prevention, Windows Information Protection and Bitlocker,Azure Information Protection P1, Delve', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E3', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '8BDBB60B-E526-43E9-92EF-AB760C8E0B72', 'msname' => 'Microsoft 365 E5', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Audio Conferencing, Phone System, Sharepoint Online, Yammer,Microsoft Advanced Threat Analytics, Windows Defender Antivirus, Device Guard, Windows DefenderAdvanced Threat Protection, Office 365 Threat Intelligence, Azure Active Directory P2, Window Hello and Credential Guard, Intune, Office 365 Data Loss Prevention, Windows Information Protection andBitlocker, Azure INformation Protection P1, Delve, Power BI Pro, Myanalytics, Advanced eDiscovery,Customer Lockbox, Advanced Data Governances', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E5', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '51E95709-DC35-4780-9040-22278CB7C0E1', 'msname' => 'Intune', 'text' => '', 'group' => 'overige', 'name' => 'Intune', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '3F22D04E-9353-46C1-BF48-B6B0C0A55A66', 'msname' => 'Visio Online Plan 1', 'text' => '', 'group' => 'overige', 'name' => 'Visio Online Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'B4D4B7F4-4089-43B6-9C44-DE97B760FB11', 'msname' => 'Visio Online Plan 2', 'text' => '', 'group' => 'overige', 'name' => 'Visio Online Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '90D3615E-AA96-478E-B6CE-8EB1E9A96B4B', 'msname' => 'One Drive for Business (Plan 1)', 'text' => '', 'group' => 'overige', 'name' => 'One Drive Business Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'BF1F6907-1F8E-4F05-B327-4896D1395C15', 'msname' => 'One Drive for Business (Plan 2)', 'text' => '', 'group' => 'overige', 'name' => 'One Drive Business Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'A56BAA74-D4E3-49FD-B228-CA0B62D08BAD', 'msname' => 'Project Online Professional', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Professional', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'A4179D30-CC09-49F0-977E-DC2CB70B874F', 'msname' => 'Project Online Essentials', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Essentials', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'D85C8762-22E4-44C0-97FE-27ED3FC4E61A', 'msname' => 'Project Online Premium', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Premium', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => 'ACA0C06C-890D-4ABB-83CF-BC519A2565E5', 'msname' => 'Skype for Business Online (Plan 1)', 'text' => '', 'group' => 'overige', 'name' => 'Skype for Business Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 7, 'code' => '14C61739-B45A-42C0-832C-D330972D3173', 'msname' => 'Skype for Business Online (Plan 2)', 'text' => '', 'group' => 'overige', 'name' => 'Skype for Business Plan 2', 'created_at' => $now, 'updated_at' => $now],

            ['product_id' => 8, 'code' => '195416C1-3447-423A-B37B-EE59A99A19C4', 'msname' => 'Exchange Online (Plan 1)', 'text' => 'Veilige en betrouwbare zakelijke e-mail met een postvak van 50 GB per gebruiker.', 'group' => 'exchange', 'name' => 'Exchange Online', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '2F707C7C-2433-49A5-A437-9CA7CF40D3EB', 'msname' => 'Exchange Online (Plan 2)', 'text' => 'Alle functies van Exchange Online plan 1, maar 100 GB opslag per mailbox, onbeperkte opslag in het in-place archief, gehoste voicemail en preventie van gegevensverlies.', 'group' => 'exchange', 'name' => 'Exchange Online Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'BD938F12-058F-4927-BBA3-AE36B1D2501C', 'msname' => 'Office 365 Business Essentials', 'text' => 'Inclusief e-mail via Exchange Online, online versies van Word, Excel en Powerpoint, Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Planner.  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business Essentials', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '5C9FD4CC-EDCE-44A8-8E91-07DF09744609', 'msname' => 'Office 365 Business', 'text' => 'Inclusief desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - niet compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker).  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '031C9E47-4802-4248-838E-778FB1D2CC05', 'msname' => 'Office 365 Business Premium', 'text' => 'Inclusief e-mail via Exchange Onlinte, desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - niet compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Outlook Customer Manager, Bookings, Planner.  Maximaal 300 gebruikers.', 'group' => 'business', 'name' => 'Office 365 Business Premium', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '91FD106F-4B2C-4938-95AC-F54F74E9A239', 'msname' => 'Office 365 Enterprise E1', 'text' => 'Inclusief e-mail via Exchange Online, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Yammer, Planner. Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 - E1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '796B6B5F-613C-4E24-A17C-EBA730D49C02', 'msname' => 'Office 365 Enterprise E3', 'text' => 'Inclusief e-mail via Exchange Online, desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - compatibel met Remote Desktop Servers), Onenote,online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker), Sharepoint Online, Teams, Yammer, Planner.  Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 - E3', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'BE57FF4C-100C-4F1F-B82D-F1C5AB63A665', 'msname' => 'Office 365 ProPlus', 'text' => 'Inclusief desktopversies van Outlook, Word, Excel, Powerpoint, Access en Publisher (5 apparaten per gebruiker - compatibel met Remote Desktop Servers), Onenote, online versies van Word, Excel en Powerpoint,  Onedrive (1TB/gebruiker).  Onbeperkt aantal gebruikers.', 'group' => 'enterprise', 'name' => 'Office 365 Pro Plus', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '61795CAB-2ABD-43F6-88E9-C9ADAE5746E0', 'msname' => 'Microsoft 365 Business', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Office 365 Data Loss Prevention, Windows Information Protectionand Bitlocker, Azure Information Protection P1, Azure Information Protection P2, Microsoft cloudApp Security, Office 365 Cloud App Security, Advanced eDiscovery, Customer Lockbox, AdvancedData Governance', 'group' => 'microsoft', 'name' => 'Microsoft 365 Business', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '2B3B8D2D-10AA-4BE4-B5FD-7F2FEB0C3091', 'msname' => 'Microsoft 365 E3', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Sharepoint Online, Yammer, Microsoft Advanced Threat Analytics,Windows Defender Antivirus, Device Guard, Azure Active Directory P1, Windows Hello and CredentialGuard, Intune, Office 365 Data Loss Prevention, Windows Information Protection and Bitlocker,Azure Information Protection P1, Delve', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E3', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '8BDBB60B-E526-43E9-92EF-AB760C8E0B72', 'msname' => 'Microsoft 365 E5', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Audio Conferencing, Phone System, Sharepoint Online, Yammer,Microsoft Advanced Threat Analytics, Windows Defender Antivirus, Device Guard, Windows DefenderAdvanced Threat Protection, Office 365 Threat Intelligence, Azure Active Directory P2, Window Hello and Credential Guard, Intune, Office 365 Data Loss Prevention, Windows Information Protection andBitlocker, Azure INformation Protection P1, Delve, Power BI Pro, Myanalytics, Advanced eDiscovery,Customer Lockbox, Advanced Data Governances', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E5', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '51E95709-DC35-4780-9040-22278CB7C0E1', 'msname' => 'Intune', 'text' => '', 'group' => 'overige', 'name' => 'Intune', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '3F22D04E-9353-46C1-BF48-B6B0C0A55A66', 'msname' => 'Visio Online Plan 1', 'text' => '', 'group' => 'overige', 'name' => 'Visio Online Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'B4D4B7F4-4089-43B6-9C44-DE97B760FB11', 'msname' => 'Visio Online Plan 2', 'text' => '', 'group' => 'overige', 'name' => 'Visio Online Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '90D3615E-AA96-478E-B6CE-8EB1E9A96B4B', 'msname' => 'One Drive for Business (Plan 1)', 'text' => '', 'group' => 'overige', 'name' => 'One Drive Business Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'BF1F6907-1F8E-4F05-B327-4896D1395C15', 'msname' => 'One Drive for Business (Plan 2)', 'text' => '', 'group' => 'overige', 'name' => 'One Drive Business Plan 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'A56BAA74-D4E3-49FD-B228-CA0B62D08BAD', 'msname' => 'Project Online Professional', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Professional', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'A4179D30-CC09-49F0-977E-DC2CB70B874F', 'msname' => 'Project Online Essentials', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Essentials', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'D85C8762-22E4-44C0-97FE-27ED3FC4E61A', 'msname' => 'Project Online Premium', 'text' => '', 'group' => 'overige', 'name' => 'Project Online Premium', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => 'ACA0C06C-890D-4ABB-83CF-BC519A2565E5', 'msname' => 'Skype for Business Online (Plan 1)', 'text' => '', 'group' => 'overige', 'name' => 'Skype for Business Plan 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 8, 'code' => '14C61739-B45A-42C0-832C-D330972D3173', 'msname' => 'Skype for Business Online (Plan 2)', 'text' => '', 'group' => 'overige', 'name' => 'Skype for Business Plan 2', 'created_at' => $now, 'updated_at' => $now],

            ['product_id' => 9, 'code' => '61795CAB-2ABD-43F6-88E9-C9ADAE5746E0', 'msname' => 'Microsoft 365 Business', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Office 365 Data Loss Prevention, Windows Information Protection and Bitlocker, Azure Information Protection P1, Azure Information Protection P2, Microsoft cloud App Security, Office 365 Cloud App Security, Advanced eDiscovery, Customer Lockbox, Advanced Data Governance', 'group' => 'microsoft', 'name' => 'Microsoft 365 Business', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 9, 'code' => '2B3B8D2D-10AA-4BE4-B5FD-7F2FEB0C3091', 'msname' => 'Microsoft 365 E3', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Sharepoint Online, Yammer, Microsoft Advanced Threat Analytics, Windows Defender Antivirus, Device Guard, Azure Active Directory P1, Windows Hello and Credential Guard, Intune, Office 365 Data Loss Prevention, Windows Information Protection and Bitlocker, Azure Information Protection P1, Delve', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E3', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 9, 'code' => '8BDBB60B-E526-43E9-92EF-AB760C8E0B72', 'msname' => 'Microsoft 365 E5', 'text' => 'Inclusief Windows 10 Pro upgrade, Word, Excel, Powerpoint (web & PC), Access (enkel PC), Outlook & Exchange, Teams, Audio Conferencing, Phone System, Sharepoint Online, Yammer, Microsoft Advanced Threat Analytics, Windows Defender Antivirus, Device Guard, Windows DefenderAdvanced Threat Protection, Office 365 Threat Intelligence, Azure Active Directory P2, Window Hello and Credential Guard, Intune, Office 365 Data Loss Prevention, Windows Information Protection andBitlocker, Azure INformation Protection P1, Delve, Power BI Pro, Myanalytics, Advanced eDiscovery,Customer Lockbox, Advanced Data Governances', 'group' => 'microsoft', 'name' => 'Microsoft 365 - E5', 'created_at' => $now, 'updated_at' => $now],
        ]);

        ProductOption::insert([
            ['product_id' => 28, 'varname' => 'processor', 'name' => 'Processors', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'memory', 'name' => 'Memory', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'disk1', 'name' => 'Disk 1', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'disk2', 'name' => 'Disk 2', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'ipv4', 'name' => 'Public IP-adres (IPv4)', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'system', 'name' => 'Operating system', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'backup', 'name' => 'Back-up', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'services', 'name' => 'Terminal Services', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'standard', 'name' => 'MS Office Standard', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'proplus', 'name' => 'MS Office Pro Plus', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'word', 'name' => 'MS Word ', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'excel', 'name' => 'MS Excel', 'created_at' => $now, 'updated_at' => $now],
            ['product_id' => 28, 'varname' => 'outlook', 'name' => 'MS Outlook', 'created_at' => $now, 'updated_at' => $now]
        ]);
    }
}
